# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5290310e877ebf19475343a484fb5b8594cbf6247161d939edd2c4769cf60bb001d6c1ff2d9b1657c7953d74d5c03dca0008ea88e0d165aaddad869390b2942e

test:
  secret_key_base: de538a708a74e6b6b2624522b3f218cdc7e497dfed93bfbe58888e62dc04686e57067ba82524b0273b2d0b8496a31342a1d5850d77c4fa99bf5e93e35d9b6c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
